# Generated by Django 5.0.2 on 2024-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
    ]
