# Generated by Django 5.0.2 on 2024-03-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='specializations',
            field=models.JSONField(default=''),
        ),
    ]
