# Generated by Django 5.0.2 on 2024-03-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_specialization_remove_doctorinfo_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='specializations',
            field=models.JSONField(default=dict),
        ),
    ]
