# Generated by Django 5.0.2 on 2024-03-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_doctorinfo_specializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='category',
        ),
    ]
