# Generated by Django 5.0.3 on 2024-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_specialization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='bio',
            field=models.TextField(default='', max_length=350, null=True),
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='specializations',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='specializations',
            field=models.ManyToManyField(to='base.specialization'),
        ),
    ]
