# Generated by Django 5.0.3 on 2024-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_doctorinfo_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
