# Generated by Django 5.0.3 on 2024-03-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_doctorinfo_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='rate',
        ),
    ]
