# Generated by Django 5.0.3 on 2024-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_doctorinfo_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='lorem',
            field=models.TextField(default='', max_length=350, null=True),
        ),
    ]
