# Generated by Django 5.0.2 on 2024-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_doctorinfo_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
