# Generated by Django 5.0.2 on 2024-04-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_message'),
        ('base', '0014_alter_user_friends'),
    ]

    operations = [
    ]
