# Generated by Django 5.0.2 on 2024-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_message_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Connector1', models.CharField(max_length=100)),
                ('Connector2', models.CharField(max_length=100)),
            ],
        ),
    ]
