# Generated by Django 5.0.2 on 2024-05-30 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='Connector1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector1_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='Connector2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector2_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
