# Generated by Django 5.0.2 on 2024-05-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorinfo',
            old_name='lorem',
            new_name='encouragement',
        ),
    ]
